version: '3'
services:
  db:
    platform: linux/x86_64
    image: mysql:5.7
    hostname: db
    volumes:
      - db_data:/var/lib/mysql
    environment:
      MYSQL_ROOT_PASSWORD: 
      MYSQL_DATABASE: master-bagasi
      MYSQL_ALLOW_EMPTY_PASSWORD: 1
    ports:
      - "3306:3306"

volumes:
  db_data: